import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ConflictException,
  InternalServerErrorException,
  ForbiddenException,
  Logger,
  Optional,
} from '@nestjs/common';
import { InjectRepository, InjectDataSource } from '@nestjs/typeorm';
import { Repository, DataSource, In } from 'typeorm';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';
import {
  Booking,
  BookingStatus,
  PaymentStatus,
  Payment,
} from '../../database/patient/entities';
import {
  AvailabilitySlot,
  DoctorProfile,
  User,
  PlatformSetting,
} from '../../database/operational/entities';
import { PaymentsService } from '../payments/payments.service';
import { NotificationsService } from '../notifications/notifications.service';
import { ReminderScheduler } from '../queues/reminder.scheduler';
import { QUEUES } from '../queues/queue.constants';

export interface CreateBookingDto {
  slotId: string;
  notes?: string;
  reasonCategory?: string;
  attachments?: { name: string; url: string; fileType: string; sizeBytes?: number }[];
  doctorId?: string;
}

export interface StitchedBookingResponse extends Booking {
  doctor?: {
    id: string;
    fullName: string;
    email: string;
    specialty: string;
    hpcsaNumber: string;
    ratePerHour: number;
    avatarUrl?: string | null;
    facilityName?: string | null;
    facilityAddress?: string | null;
  };
  patient?: {
    id: string;
    fullName: string;
    email: string;
    phone?: string;
  };
  slot?: {
    id: string;
    startTime: Date;
    endTime: Date;
  };
  payment?: Payment | null;
}

@Injectable()
export class BookingsService {
  private readonly logger = new Logger(BookingsService.name);

  constructor(
    @InjectRepository(Booking, 'patient')
    private readonly bookingRepository: Repository<Booking>,
    @InjectRepository(Payment, 'patient')
    private readonly paymentRepository: Repository<Payment>,
    @InjectRepository(AvailabilitySlot, 'operational')
    private readonly slotRepository: Repository<AvailabilitySlot>,
    @InjectRepository(DoctorProfile, 'operational')
    private readonly doctorRepository: Repository<DoctorProfile>,
    @InjectRepository(User, 'operational')
    private readonly userRepository: Repository<User>,
    @InjectRepository(PlatformSetting, 'operational')
    private readonly platformSettingRepository: Repository<PlatformSetting>,
    @InjectDataSource('operational')
    private readonly operationalDataSource: DataSource,
    @InjectDataSource('patient')
    private readonly patientDataSource: DataSource,
    private readonly paymentsService: PaymentsService,
    @InjectQueue(QUEUES.BOOKING_DLQ)
    private readonly dlqQueue: Queue,
    @Optional()
    private readonly notificationsService?: NotificationsService,
    @Optional()
    private readonly reminderScheduler?: ReminderScheduler,
  ) {}

  /**
   * BE-501: Booking Creation Saga Orchestrator.
   * Atomic slot reservation on VPS Postgres with compensating rollback
   * and DLQ fallback on AWS RDS write failure.
   */
  async createBookingSaga(
    patientId: string,
    dto: CreateBookingDto,
  ): Promise<StitchedBookingResponse> {
    const { slotId } = dto;
    this.logger.log(`Starting Booking Creation Saga for slotId=${slotId}, patientId=${patientId}`);

    // =========================================================================
    // STEP 1: VPS Postgres (Operational DB) — Atomic Slot Lock
    // =========================================================================
    const vpsQueryRunner = this.operationalDataSource.createQueryRunner();
    await vpsQueryRunner.connect();
    await vpsQueryRunner.startTransaction();

    let lockedSlot: AvailabilitySlot | null = null;
    let doctorProfile: DoctorProfile | null = null;

    try {
      // Pessimistic write lock: SELECT ... FOR UPDATE
      lockedSlot = await vpsQueryRunner.manager
        .createQueryBuilder(AvailabilitySlot, 'slot')
        .setLock('pessimistic_write')
        .where('slot.id = :slotId', { slotId })
        .getOne();

      if (!lockedSlot) {
        // Handle synthetic slot (e.g., slot-YYYY-MM-DD-HH:mm) generated by the booking calendar
        const match = slotId.match(/^slot-(\d{4}-\d{2}-\d{2})-(\d{1,2}:\d{2})$/);
        if (match) {
          const [, slotDateStr, slotTimeStr] = match;
          const [h, m] = slotTimeStr.split(':').map(Number);
          const start = new Date(`${slotDateStr}T00:00:00`);
          start.setHours(h, m, 0, 0);
          const end = new Date(start.getTime() + 45 * 60 * 1000);

          // Strictly prevent booking past dates and times
          if (start.getTime() <= Date.now()) {
            throw new BadRequestException('Cannot book a slot in the past');
          }

          // Resolve doctor profile
          if (dto.doctorId) {
            doctorProfile = await vpsQueryRunner.manager.findOne(DoctorProfile, {
              where: [{ id: dto.doctorId }, { slug: dto.doctorId }],
              relations: ['user'],
            });
          }
          if (!doctorProfile) {
            doctorProfile = await vpsQueryRunner.manager.findOne(DoctorProfile, {
              relations: ['user'],
            });
          }

          if (!doctorProfile) {
            throw new NotFoundException('Doctor profile associated with this slot was not found');
          }

          // Create and persist the locked AvailabilitySlot on VPS Postgres
          const newSlot = vpsQueryRunner.manager.create(AvailabilitySlot, {
            doctor_id: doctorProfile.id,
            start_time: start,
            end_time: end,
            is_booked: true,
            is_locked: false,
          });
          lockedSlot = await vpsQueryRunner.manager.save(AvailabilitySlot, newSlot);
        } else {
          throw new NotFoundException(`Availability slot with ID ${slotId} not found`);
        }
      } else {
        if (lockedSlot.is_booked) {
          throw new ConflictException('This appointment slot has already been booked');
        }

        if (lockedSlot.is_locked) {
          throw new ConflictException('This appointment slot is currently locked');
        }

        // Check slot is in future
        if (new Date(lockedSlot.start_time).getTime() <= Date.now()) {
          throw new BadRequestException('Cannot book a slot in the past');
        }

        // Retrieve doctor profile to determine consultation price
        doctorProfile = await vpsQueryRunner.manager.findOne(DoctorProfile, {
          where: { id: lockedSlot.doctor_id },
          relations: ['user'],
        });

        if (!doctorProfile) {
          throw new NotFoundException('Doctor profile associated with this slot was not found');
        }

        // Mark slot as booked on VPS
        lockedSlot.is_booked = true;
        await vpsQueryRunner.manager.save(lockedSlot);
      }

      // Commit Step 1 on VPS Postgres
      await vpsQueryRunner.commitTransaction();
      this.logger.log(`Step 1 Success: Slot ${slotId} locked and committed on VPS Postgres`);
    } catch (err: any) {
      await vpsQueryRunner.rollbackTransaction();
      this.logger.warn(`Step 1 Aborted: ${err.message}`);
      throw err;
    } finally {
      await vpsQueryRunner.release();
    }

    // =========================================================================
    // STEP 2: AWS RDS (Patient DB) — Insert Booking Record
    // =========================================================================
    const price = Number(doctorProfile.rate_per_hour) || 850.0;
    const commissionAmount = Math.round(price * 0.15 * 100) / 100; // 15% platform commission

    let createdBooking: Booking;

    try {
      const newBooking = this.bookingRepository.create({
        patient_id: patientId,
        doctor_id: lockedSlot.doctor_id,
        slot_id: lockedSlot.id,
        status: BookingStatus.PENDING,
        price,
        commission_amount: commissionAmount,
        payment_status: PaymentStatus.UNPAID,
        notes: dto.notes || null,
        reason_category: dto.reasonCategory || null,
        attachments: dto.attachments || null,
      });

      createdBooking = await this.bookingRepository.save(newBooking);
      this.logger.log(`Step 2 Success: Booking ${createdBooking.id} created on AWS RDS`);
    } catch (rdsError: any) {
      this.logger.error(
        `Step 2 Failed writing to AWS RDS: ${rdsError.message}. Initiating compensating rollback on VPS Postgres.`,
      );

      // =======================================================================
      // COMPENSATING ROLLBACK: Revert slot is_booked on VPS Postgres
      // =======================================================================
      try {
        await this.slotRepository.update(
          { id: lockedSlot.id },
          { is_booked: false },
        );
        this.logger.log(`Compensating Rollback Success: Slot ${lockedSlot.id} released on VPS Postgres`);
      } catch (compensateError: any) {
        // Step 1 rollback failed! Push to Dead-Letter Queue (DLQ) for Reconciliation Cron
        this.logger.error(
          `CRITICAL: Compensating rollback failed on VPS! Pushing slot ${lockedSlot.id} to DLQ: ${compensateError.message}`,
        );

        try {
          await this.dlqQueue.add(
            'booking-compensation-failed',
            {
              slotId: lockedSlot.id,
              doctorId: lockedSlot.doctor_id,
              patientId,
              timestamp: new Date().toISOString(),
              action: 'release_slot',
              error: compensateError.message,
            },
            { attempts: 5, backoff: 5000 },
          );
        } catch (dlqError: any) {
          this.logger.error(`Failed to push to DLQ queue: ${dlqError.message}`);
        }
      }

      throw new InternalServerErrorException(
        'Unable to complete booking reservation. All database modifications have been safely compensated.',
      );
    }

    // Return stitched response
    return this.stitchBooking(createdBooking, doctorProfile, lockedSlot);
  }

  /**
   * BE-506: Cross-Database Booking Queries — Mine (Patient).
   * Stitches RDS bookings with VPS DoctorProfile, User, and AvailabilitySlot data.
   */
  async getPatientBookings(patientId: string): Promise<StitchedBookingResponse[]> {
    const bookings = await this.bookingRepository.find({
      where: { patient_id: patientId },
      order: { created_at: 'DESC' },
    });

    if (bookings.length === 0) return [];
    return this.enrichBookings(bookings);
  }

  /**
   * BE-506: Cross-Database Booking Queries — Doctor.
   * Stitches RDS bookings with Patient User and AvailabilitySlot data.
   */
  async getDoctorBookings(doctorIdOrUserId: string): Promise<StitchedBookingResponse[]> {
    if (!doctorIdOrUserId) return [];

    const conditions: Array<{ doctor_id: string }> = [{ doctor_id: doctorIdOrUserId }];

    const doctorProfile = await this.doctorRepository.findOne({
      where: [{ user_id: doctorIdOrUserId }, { id: doctorIdOrUserId }],
    });

    if (doctorProfile) {
      conditions.push({ doctor_id: doctorProfile.id });
      if (doctorProfile.user_id) {
        conditions.push({ doctor_id: doctorProfile.user_id });
      }
    }

    // Also include any bookings tied to slots owned by this doctor
    let slotIds: string[] = [];
    if (doctorProfile) {
      const doctorSlots = await this.slotRepository.find({
        where: { doctor_id: doctorProfile.id },
        select: ['id'],
      });
      slotIds = doctorSlots.map((s) => s.id);
    }

    let bookings: Booking[] = [];
    if (slotIds.length > 0) {
      bookings = await this.bookingRepository.find({
        where: [
          ...conditions,
          { slot_id: In(slotIds) },
        ],
        order: { created_at: 'DESC' },
      });
    } else {
      bookings = await this.bookingRepository.find({
        where: conditions,
        order: { created_at: 'DESC' },
      });
    }

    if (bookings.length === 0) return [];
    return this.enrichBookings(bookings);
  }

  /**
   * BE-506: Cross-Database Booking Queries — Single Booking Details.
   */
  async getBookingById(id: string, requesterUserId?: string): Promise<StitchedBookingResponse> {
    const booking = await this.bookingRepository.findOne({
      where: { id },
    });

    if (!booking) {
      throw new NotFoundException(`Booking ${id} not found`);
    }

    const enrichedList = await this.enrichBookings([booking]);
    const enriched = enrichedList[0];

    // Fetch payments if any
    const payment = await this.paymentRepository.findOne({
      where: { booking_id: id },
      order: { created_at: 'DESC' },
    });
    enriched.payment = payment || null;

    return enriched;
  }

  /**
   * BE-507 & BE-801: 24-Hour Cancellation & Deduction Policy Engine.
   * Computes >=24h vs <24h rules, allocates penalty deduction to doctor,
   * executes refund or credit issuance, cancels BullMQ reminders,
   * and reopens availability slot on VPS.
   */
  async cancelBooking(
    bookingId: string,
    userId: string,
    reason?: string,
    action: 'refund' | 'credit' = 'refund',
  ) {
    this.logger.log(
      `Cancelling booking ${bookingId} requested by user ${userId} with action=${action}`,
    );

    const booking = await this.bookingRepository.findOne({
      where: { id: bookingId },
    });

    if (!booking) {
      throw new NotFoundException(`Booking ${bookingId} not found`);
    }

    if (booking.status === BookingStatus.CANCELLED) {
      throw new BadRequestException('Booking is already cancelled');
    }

    if (booking.status === BookingStatus.COMPLETED) {
      throw new BadRequestException('Cannot cancel a completed booking');
    }

    // Check authorization: must be patient, or doctor of the booking
    const isPatient = booking.patient_id === userId;
    let isDoctor = booking.doctor_id === userId;
    let doctorProfile: DoctorProfile | null = null;

    if (!isPatient && !isDoctor) {
      doctorProfile = await this.doctorRepository.findOne({
        where: { user_id: userId },
      });
      if (doctorProfile && doctorProfile.id === booking.doctor_id) {
        isDoctor = true;
      } else {
        throw new ForbiddenException('You are not authorized to cancel this booking');
      }
    }

    // Fetch slot to compute 24-hour threshold
    const slot = await this.slotRepository.findOne({
      where: { id: booking.slot_id },
      relations: ['doctor', 'doctor.user'],
    });

    const now = Date.now();
    const slotStartMs = slot ? new Date(slot.start_time).getTime() : now;
    const hoursUntilAppointment = (slotStartMs - now) / (1000 * 60 * 60);
    const isOver24Hours = hoursUntilAppointment >= 24;

    // Fetch platform setting for late cancellation deduction
    let lateDeductionPercent = 30.0;
    try {
      const settings = await this.platformSettingRepository?.findOne({ where: {} });
      if (settings?.late_cancellation_deduction_percent !== undefined) {
        lateDeductionPercent = Number(settings.late_cancellation_deduction_percent);
      }
    } catch (_) {}

    const totalPrice = Number(booking.price);
    let deductionAmount = 0;
    let remainderAmount = totalPrice;

    // Doctor initiated cancellation (any time) -> 100% full refund to patient
    // Patient initiated cancellation:
    // >= 24h: 100% refund (card or credit)
    // < 24h: configured deduction % (e.g. 30%) allocated to doctor, remainder (70%) to patient
    if (isPatient && !isOver24Hours) {
      deductionAmount = Math.round(totalPrice * (lateDeductionPercent / 100) * 100) / 100;
      remainderAmount = Math.max(0, totalPrice - deductionAmount);
      this.logger.log(
        `Late cancellation (<24h). Price=${totalPrice}, deduction=${deductionAmount} (${lateDeductionPercent}%), remainder=${remainderAmount}`,
      );
    }

    // Process refund / platform credit
    let refundResult = null;
    if (booking.payment_status === PaymentStatus.HELD || booking.payment_status === PaymentStatus.UNPAID) {
      if (action === 'credit') {
        // Option A: 100% Platform Credit (never expires)
        await this.paymentsService.addWalletCredit(
          booking.patient_id,
          remainderAmount,
          reason || `Platform credit for cancelled booking ${booking.id}`,
          booking.id,
        );
        booking.payment_status = PaymentStatus.REFUNDED;
        refundResult = {
          success: true,
          refund_method: 'wallet',
          amount: remainderAmount,
          message: 'Platform credit issued to wallet',
        };
      } else {
        // Option B: Cash refund to original card
        refundResult = await this.paymentsService.processRefund({
          bookingId: booking.id,
          amount: remainderAmount,
          reason: reason || 'Booking cancellation',
          refundToWallet: false,
        });
      }
    }

    // Mark booking as cancelled
    booking.status = BookingStatus.CANCELLED;
    await this.bookingRepository.save(booking);

    // Reopen availability slot on VPS Postgres
    if (slot) {
      slot.is_booked = false;
      await this.slotRepository.save(slot);
    } else {
      await this.slotRepository.update({ id: booking.slot_id }, { is_booked: false });
    }

    // Cancel delayed BullMQ reminders
    if (this.reminderScheduler) {
      await this.reminderScheduler.cancelBookingReminders(booking.id);
    }

    // Multi-Channel Notifications Dispatch (BE-807)
    if (this.notificationsService) {
      const formattedDate = slot
        ? new Date(slot.start_time).toLocaleDateString('en-ZA', {
            weekday: 'long',
            year: 'numeric',
            month: 'short',
            day: 'numeric',
          })
        : 'scheduled date';

      // Alert Patient
      await this.notificationsService.dispatchNotification({
        recipientId: booking.patient_id,
        title: 'Booking Cancelled',
        templateId: 'booking_cancelled',
        payload: {
          bookingId: booking.id,
          doctorName: slot?.doctor?.user?.full_name || 'Doctor',
          appointmentDate: formattedDate,
          refundStatus: isOver24Hours
            ? '100% full refund processed'
            : `Late cancellation: R${deductionAmount.toFixed(2)} allocated to doctor, remainder R${remainderAmount.toFixed(2)} processed.`,
          creditAmount: action === 'credit' ? remainderAmount : null,
          message: `Your booking for ${formattedDate} has been cancelled.`,
        },
        deepLink: `/bookings`,
      });

      // Alert Doctor
      const doctorUserId = slot?.doctor?.user_id;
      if (doctorUserId) {
        await this.notificationsService.dispatchNotification({
          recipientId: doctorUserId,
          title: 'Appointment Cancelled',
          templateId: 'booking_cancelled',
          payload: {
            bookingId: booking.id,
            appointmentDate: formattedDate,
            deductionAmount,
            message: deductionAmount > 0
              ? `Appointment for ${formattedDate} was cancelled within 24h. Late cancellation fee of R${deductionAmount.toFixed(2)} allocated to you.`
              : `Appointment for ${formattedDate} was cancelled by patient.`,
          },
          deepLink: `/calendar`,
        });
      }
    }

    this.logger.log(`Booking ${bookingId} cancelled and slot reopened.`);

    return {
      success: true,
      booking_id: booking.id,
      status: booking.status,
      is_over_24h: isOver24Hours,
      deduction_percent: isOver24Hours || isDoctor ? 0 : lateDeductionPercent,
      deduction_amount: deductionAmount,
      refund_amount: remainderAmount,
      refund_method: action === 'credit' ? 'wallet' : 'card',
      refund: refundResult,
      message: isOver24Hours
        ? 'Booking cancelled with 100% refund.'
        : `Booking cancelled within 24 hours. ${lateDeductionPercent}% (R${deductionAmount.toFixed(2)}) allocated to doctor as late fee. Remainder R${remainderAmount.toFixed(2)} processed.`,
    };
  }

  /**
   * BE-802: Appointment Rescheduling Engine.
   * Atomically swaps slot reference on VPS, updates booking on AWS RDS,
   * reschedules BullMQ reminders, and dispatches notifications.
   */
  async rescheduleBooking(
    bookingId: string,
    userId: string,
    dto: { newSlotId: string; reason?: string },
  ): Promise<StitchedBookingResponse> {
    const { newSlotId } = dto;
    this.logger.log(`Rescheduling booking ${bookingId} to slot ${newSlotId} for user ${userId}`);

    const booking = await this.bookingRepository.findOne({
      where: { id: bookingId },
    });

    if (!booking) {
      throw new NotFoundException(`Booking ${bookingId} not found`);
    }

    if (booking.status !== BookingStatus.CONFIRMED && booking.status !== BookingStatus.PENDING) {
      throw new BadRequestException(`Cannot reschedule booking in status: ${booking.status}`);
    }

    // Check authorization
    const isPatient = booking.patient_id === userId;
    let isDoctor = booking.doctor_id === userId;

    if (!isPatient && !isDoctor) {
      const doctorProfile = await this.doctorRepository.findOne({ where: { user_id: userId } });
      if (doctorProfile && doctorProfile.id === booking.doctor_id) {
        isDoctor = true;
      } else {
        throw new ForbiddenException('You are not authorized to reschedule this booking');
      }
    }

    // Fetch old slot
    const oldSlot = await this.slotRepository.findOne({ where: { id: booking.slot_id } });
    if (!oldSlot) {
      throw new NotFoundException('Current availability slot not found');
    }

    // Patient rule: >= 24h threshold
    const now = Date.now();
    const oldSlotStartMs = new Date(oldSlot.start_time).getTime();
    if (isPatient && (oldSlotStartMs - now) < 24 * 60 * 60 * 1000) {
      throw new BadRequestException(
        'Rescheduling is only permitted at least 24 hours prior to appointment start time. Within 24 hours, please cancel to apply late policy.',
      );
    }

    // Fetch new slot
    const newSlot = await this.slotRepository.findOne({
      where: { id: newSlotId },
      relations: ['doctor', 'doctor.user'],
    });

    if (!newSlot) {
      throw new NotFoundException(`Replacement slot ${newSlotId} not found`);
    }

    if (newSlot.doctor_id !== booking.doctor_id) {
      throw new BadRequestException('Replacement slot must belong to the same doctor');
    }

    if (newSlot.is_booked || newSlot.is_locked) {
      throw new ConflictException('Selected replacement slot is no longer available');
    }

    if (new Date(newSlot.start_time).getTime() <= now) {
      throw new BadRequestException('Cannot reschedule to a past time slot');
    }

    // Atomic swap on VPS DB
    const queryRunner = this.operationalDataSource.createQueryRunner();
    await queryRunner.connect();
    await queryRunner.startTransaction();

    try {
      newSlot.is_booked = true;
      await queryRunner.manager.save(AvailabilitySlot, newSlot);

      oldSlot.is_booked = false;
      await queryRunner.manager.save(AvailabilitySlot, oldSlot);

      await queryRunner.commitTransaction();
    } catch (err: any) {
      await queryRunner.rollbackTransaction();
      this.logger.error(`Atomic slot swap failed on VPS: ${err.message}`);
      throw new InternalServerErrorException('Failed to swap availability slots');
    } finally {
      await queryRunner.release();
    }

    // Update booking on AWS RDS
    booking.slot_id = newSlot.id;
    await this.bookingRepository.save(booking);

    // Reschedule BullMQ reminders
    if (this.reminderScheduler) {
      await this.reminderScheduler.cancelBookingReminders(booking.id);
      await this.reminderScheduler.scheduleBookingReminders({
        bookingId: booking.id,
        patientId: booking.patient_id,
        doctorId: booking.doctor_id,
        slotStartTime: newSlot.start_time,
        doctorName: newSlot.doctor?.user?.full_name || 'Doctor',
      });
    }

    // Dispatch notifications
    const formattedDate = new Date(newSlot.start_time).toLocaleDateString('en-ZA', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
    const formattedTime = new Date(newSlot.start_time).toLocaleTimeString('en-ZA', {
      hour: '2-digit',
      minute: '2-digit',
    });

    if (this.notificationsService) {
      // Patient notification
      await this.notificationsService.dispatchNotification({
        recipientId: booking.patient_id,
        title: 'Appointment Rescheduled',
        templateId: 'booking_rescheduled',
        payload: {
          bookingId: booking.id,
          doctorName: newSlot.doctor?.user?.full_name || 'Doctor',
          appointmentDate: formattedDate,
          appointmentTime: formattedTime,
          message: `Your appointment with Dr. ${newSlot.doctor?.user?.full_name || 'Doctor'} has been rescheduled to ${formattedDate} at ${formattedTime}.`,
        },
        deepLink: `/bookings/${booking.id}`,
      });

      // Doctor notification
      const doctorUser = newSlot.doctor?.user_id;
      if (doctorUser) {
        await this.notificationsService.dispatchNotification({
          recipientId: doctorUser,
          title: 'Appointment Rescheduled',
          templateId: 'booking_rescheduled',
          payload: {
            bookingId: booking.id,
            appointmentDate: formattedDate,
            appointmentTime: formattedTime,
            message: `An appointment was rescheduled to ${formattedDate} at ${formattedTime}.`,
          },
          deepLink: `/calendar`,
        });
      }
    }

    this.logger.log(`Booking ${bookingId} successfully rescheduled to slot ${newSlotId}`);
    return this.getBookingById(booking.id, userId);
  }

  /**
   * Update or attach patient intake details, symptoms notes, and medical test reports.
   */
  async updateBookingIntake(
    bookingId: string,
    userId: string,
    dto: { notes?: string; reasonCategory?: string; attachments?: any[] },
  ): Promise<StitchedBookingResponse> {
    const booking = await this.bookingRepository.findOne({
      where: { id: bookingId },
    });

    if (!booking) {
      throw new NotFoundException(`Booking ${bookingId} not found`);
    }

    // Authorize: patient or doctor
    let isAuthorized = booking.patient_id === userId || booking.doctor_id === userId;
    if (!isAuthorized) {
      const doctorProfile = await this.doctorRepository.findOne({ where: { user_id: userId } });
      if (doctorProfile && doctorProfile.id === booking.doctor_id) {
        isAuthorized = true;
      }
    }

    if (!isAuthorized) {
      throw new ForbiddenException('Not authorized to update this booking intake');
    }

    if (dto.notes !== undefined) {
      booking.notes = dto.notes;
    }
    if (dto.reasonCategory !== undefined) {
      booking.reason_category = dto.reasonCategory;
    }
    if (dto.attachments !== undefined) {
      // Merge or replace attachments
      const existing = booking.attachments || [];
      const incoming = Array.isArray(dto.attachments) ? dto.attachments : [];
      // Combine unique by URL or name
      const existingUrls = new Set(existing.map((a) => a.url));
      const combined = [...existing, ...incoming.filter((a) => !existingUrls.has(a.url))];
      booking.attachments = combined;
    }

    await this.bookingRepository.save(booking);
    this.logger.log(`Booking ${bookingId} clinical intake updated by user ${userId}`);
    return this.getBookingById(bookingId, userId);
  }

  /**
   * BE-508: Cross-DB Reconciliation Cron Job.
   * Scans for orphaned `is_booked = true` slots lacking active bookings,
   * cancels expired pending bookings, and drains DLQ items.
   */
  async reconcileDatabaseDrift() {
    this.logger.log('Starting cross-database reconciliation audit...');
    let orphanedSlotsFixed = 0;
    let expiredPendingFixed = 0;
    let dlqProcessed = 0;

    // 1. Scan VPS slots marked booked
    const bookedSlots = await this.slotRepository.find({
      where: { is_booked: true },
    });

    if (bookedSlots.length > 0) {
      const slotIds = bookedSlots.map((s) => s.id);
      const activeBookings = await this.bookingRepository.find({
        where: { slot_id: In(slotIds) },
      });

      const slotBookingMap = new Map<string, Booking>();
      for (const b of activeBookings) {
        slotBookingMap.set(b.slot_id, b);
      }

      const now = Date.now();
      const thirtyMinutesAgo = now - 30 * 60 * 1000;

      for (const slot of bookedSlots) {
        const booking = slotBookingMap.get(slot.id);

        if (!booking) {
          // Orphaned slot with no booking in RDS!
          this.logger.warn(`[Reconciliation] Orphaned slot detected: id=${slot.id}. Releasing slot.`);
          slot.is_booked = false;
          await this.slotRepository.save(slot);
          orphanedSlotsFixed++;
        } else if (
          booking.status === BookingStatus.PENDING &&
          booking.payment_status === PaymentStatus.UNPAID &&
          new Date(booking.created_at).getTime() < thirtyMinutesAgo
        ) {
          // Expired pending booking older than 30 mins without payment!
          this.logger.warn(
            `[Reconciliation] Expired pending booking detected: id=${booking.id}, slotId=${slot.id}. Cancelling.`,
          );
          booking.status = BookingStatus.CANCELLED;
          await this.bookingRepository.save(booking);

          slot.is_booked = false;
          await this.slotRepository.save(slot);
          expiredPendingFixed++;
        } else if (booking.status === BookingStatus.CANCELLED) {
          // Slot still marked booked even though booking is cancelled
          this.logger.warn(`[Reconciliation] Slot ${slot.id} marked booked for cancelled booking ${booking.id}. Fixing.`);
          slot.is_booked = false;
          await this.slotRepository.save(slot);
          orphanedSlotsFixed++;
        }
      }
    }

    // 2. Process DLQ Queue Jobs
    try {
      const waitingJobs = await this.dlqQueue.getWaiting();
      for (const job of waitingJobs) {
        if (job.data?.action === 'release_slot' && job.data?.slotId) {
          await this.slotRepository.update({ id: job.data.slotId }, { is_booked: false });
          await job.remove();
          dlqProcessed++;
        }
      }
    } catch (e: any) {
      this.logger.warn(`Could not drain DLQ queue during reconciliation: ${e.message}`);
    }

    this.logger.log(
      `Reconciliation complete: ${orphanedSlotsFixed} orphaned slots fixed, ${expiredPendingFixed} expired pending bookings fixed, ${dlqProcessed} DLQ entries processed.`,
    );

    return {
      success: true,
      timestamp: new Date().toISOString(),
      orphaned_slots_fixed: orphanedSlotsFixed,
      expired_pending_fixed: expiredPendingFixed,
      dlq_processed: dlqProcessed,
    };
  }

  // =========================================================================
  // Private Helper Stitching Methods
  // =========================================================================

  private async enrichBookings(bookings: Booking[]): Promise<StitchedBookingResponse[]> {
    const doctorIds = [...new Set(bookings.map((b) => b.doctor_id))];
    const patientIds = [...new Set(bookings.map((b) => b.patient_id))];
    const slotIds = [...new Set(bookings.map((b) => b.slot_id))];

    // Fetch doctors from operational DB
    const doctors = doctorIds.length > 0
      ? await this.doctorRepository.find({
          where: { id: In(doctorIds) },
          relations: ['user'],
        })
      : [];
    const doctorMap = new Map<string, DoctorProfile>();
    doctors.forEach((d) => doctorMap.set(d.id, d));

    // Fetch patient users from operational DB
    const patients = patientIds.length > 0
      ? await this.userRepository.find({
          where: { id: In(patientIds) },
        })
      : [];
    const patientMap = new Map<string, User>();
    patients.forEach((p) => patientMap.set(p.id, p));

    // Fetch slots from operational DB
    const slots = slotIds.length > 0
      ? await this.slotRepository.find({
          where: { id: In(slotIds) },
        })
      : [];
    const slotMap = new Map<string, AvailabilitySlot>();
    slots.forEach((s) => slotMap.set(s.id, s));

    return bookings.map((booking) => {
      const doc = doctorMap.get(booking.doctor_id);
      const pat = patientMap.get(booking.patient_id);
      const slt = slotMap.get(booking.slot_id);

      return this.stitchBooking(booking, doc, slt, pat);
    });
  }

  private stitchBooking(
    booking: Booking,
    doc?: DoctorProfile | null,
    slot?: AvailabilitySlot | null,
    patient?: User | null,
  ): StitchedBookingResponse {
    const response: StitchedBookingResponse = {
      ...booking,
    };

    if (doc) {
      response.doctor = {
        id: doc.id,
        fullName: doc.user?.full_name || 'Dr. Practitioner',
        email: doc.user?.email || '',
        specialty: doc.specialty,
        hpcsaNumber: doc.hpcsa_number,
        ratePerHour: Number(doc.rate_per_hour),
        avatarUrl: doc.user?.avatar_url || null,
        facilityName: doc.facility_name || null,
        facilityAddress: doc.facility_address || null,
      };
    }

    if (patient) {
      response.patient = {
        id: patient.id,
        fullName: patient.full_name,
        email: patient.email,
        phone: patient.phone,
      };
    }

    if (slot) {
      response.slot = {
        id: slot.id,
        startTime: slot.start_time,
        endTime: slot.end_time,
      };
    }

    return response;
  }
}
